###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: coinbase-memcached

    mariadb:
      image: mariadb:10.4
      container_name: coinbase-mariadb
#      working_dir: /application
      volumes:
        - /Volumes/segate/coinbase_data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=coinbase_v1
        - MYSQL_USER=coinbase_usr
        - MYSQL_PASSWORD=root
      ports:
        - "8184:3306"

    webserver:
      image: nginx:alpine
      container_name: coinbase-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8181:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: coinbase-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

